version: "3.9"
services:
  api:
    build:
      context: .  
    ports:
      - "5050:5050"
    cap_drop: 
      - all
    restart: always
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 200M
    # Remove the volume mount for production. It's a major security risk
    # volumes:
    #  - .:/code  #  COMMENTED OUT FOR PRODUCTION
    user: "appuser:appuser" # Run as non-root user
    command: uvicorn app.main:app --host 0.0.0.0 --port 5050 --reload
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"] 
      interval: 10s
      timeout: 5s
      retries: 3

