name: Docker Image CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set Docker image version
        id: vars
        run: echo "IMAGE_VERSION=v1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t poswark/python-test:${{ env.IMAGE_VERSION }} .
        
